import { Input } from "@components/Input";
import { pathGet } from "@utils/pathGet";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styled from "styled-components";

export const PageContainer = styled.main`
  text-align: center;

  form {
    width: 100vw;
    display: flex;
    justify-content: center;
    align-items: center;
  }
`;

const Home: NextPage = () => {
  const [query, setQuery] = useState("");
  const [queryError, setQueryError] = useState<string | null>(null);

  const handleSubmit = (evt: React.FormEvent<HTMLFormElement>) => {
    evt.preventDefault();

    if (!query.length) {
      setQueryError("Please enter a query");
    } else {
      const { error, message } = pathGet(query);

      if (error) {
        setQueryError(message);
        return;
      }

      alert(message);
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Press enter to search</h1>

      <form style={{}} onSubmit={handleSubmit}>
        <Input
          placeholder="Enter query"
          id="query"
          label="Query"
          error={queryError}
          onChange={(evt) => {
            queryError && setQueryError(null);
            setQuery(evt.target.value);
          }}
          value={query}
        />
      </form>
    </>
  );
};

export default Home;
